json.array! @locations,
  :id,
  :status,
  :region,
  :location,
  :name,
  :ext_id,
  :website,
  :phone,
  :location_type,
  :postal_code,
  :country_iso_code,
  :brewery_ext_id,
  :locality,
  :street_address,
  :created_at,
  :updated_at